設定画面をTCA化
KaguraGateway/cafelogos-pos pull request #55
Opened 2024-07-14 17:27 UTC by nyagasan

# やったこと
- やり残したSettingFeatureのTCA化
- BindingReducerの力で割と簡単にいけました
- クライアント名入力TextFieldの再設置
- Presentation内ファイルの全削除
  - これにてViewModelは駆逐されました 

# 確認して欲しいこと
- クライアント名の取得がうまくいかないようで、編集・保存後に再度ページを開くと編集前の名前が表示されることがある
  - よき実装があれば教えて欲しいです

2024-07-18 05:15 UTC, KaguraGateway requested changes

2024-07-18 05:15 UTC, KaguraGateway commented on LogoREGIUI/Sources/Features/SettingFeature/SettingView.swift
> +    //    @ObservedObject var viewModel = GeneralSettingViewModel()
コメント消し忘れ

2024-07-18 05:15 UTC, KaguraGateway commented on LogoREGIUI/Sources/Features/SettingFeature/SettingsFeature.swift
> +        var config: Config
公式ドキュメント見ると、`@BindingState` 必要そうだけどいらないの？（一旦適当言ってるかも）
https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/bindingreducer#overview

2024-07-18 05:15 UTC, KaguraGateway commented on LogoREGIUI/Sources/Features/SettingFeature/SettingsFeature.swift
> +                    updatedConfig.clientName = clientName
これだと `usePrinter`とかのプロパティ保存できてないので、ついでに保存できるように修正頼みます（元のviewModelだとそこらへん実装してない（強制印刷だったから））

2024-07-18 05:38 UTC, nyagasan commented on LogoREGIUI/Sources/Features/SettingFeature/SettingsFeature.swift
> +        var config: Config
確かに…？
https://github.com/pointfreeco/swift-composable-architecture/blob/1.11.2/Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift
このcase studiesの実装例みた感じ、なくても大丈夫そうだったからスルーしてたけど、ドキュメントに準拠した形で実装します！

2024-07-31 11:19 UTC, nyagasan commented on LogoREGIUI/Sources/Features/SettingFeature/SettingsFeature.swift
> +        var config: Config
調べてみたところ、
@ObservableStateが使っている、ObservationフレームワークにBinding機能が内包されているから、個別に@BindingStateをつける必要はないみたい

（@ObservableStateをつけずにBindingしたい場合に利用するとのこと）

2024-09-15 12:18 UTC, KaguraGateway approved these changes
放置してて申し訳🙏LGTM

2024-09-15 12:18 UTC, merged